language: python
python:
  - 2.7

before_install:
    # update aptitude
    - sudo apt-get update

    - sudo apt-get install python-opencv
    - sudo dpkg -L python-opencv
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7

install:
    # install python requirements
    - make setup

script:
    # finally run tests
    - make test
