language: python
python:
  - 2.7

before_install:
    # update aptitude
    - sudo apt-get update

    # help python importing cv and/or cv2
    - sudo pip install opencv-python
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7

install:
    # install python requirements
    - make setup

script:
    # finally run tests
    - make test
