language: python
python:
  - 2.7

before_install:
    # update aptitude
    - apt-get update

    - apt-get install python-opencv
    - dpkg -L python-opencv

install:
    # install python requirements
    - make setup

script:
    # finally run tests
    - make test
