language: python
python:
  - 3.5

before_install:
    # update aptitude
    - sudo add-apt-repository -y ppa:orangain/opencv
    - sudo apt-get update
    - sudo apt-get install -y python3-opencv

    # help python importing cv and/or cv2
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python3.5

    # verify all requirements were met
    - INSTALLDIR=$(python -c "import os; import numpy; import cv2; print(os.path.dirname(cv2.__file__))")

install:
    # install python requirements
    - make setup

script:
    # finally run tests
    - make test
