language: python
python:
  - 2.7

before_install:
    # update aptitude
    - sudo apt-get update

    # help python importing cv and/or cv2
    - sudo pip install python-opencv
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7

    # verify all requirements were met
    - INSTALLDIR=$(python -c "import os; import numpy; import cv2; print(os.path.dirname(cv2.__file__))")

install:
    # install python requirements
    - make setup

script:
    # finally run tests
    - make test
